# Generated by Django 5.2.9 on 2025-12-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image_field',
            field=models.CharField(default=''),
        ),
    ]
