# Generated by Django 5.2.9 on 2025-12-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image_field',
            field=models.CharField(blank=True),
        ),
    ]
