# Generated by Django 5.2.9 on 2025-12-17 01:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_collaborationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image_field',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
