# Generated by Django 5.2.9 on 2025-12-18 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_about_image_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='image_field',
            new_name='profile_image',
        ),
    ]
